CREATE TABLE CLIENTES
  (ID INT NOT NULL,   
   NOMBRE VARCHAR(50) , 
   APELLIDO1 VARCHAR(50) ,
   APELLIDO2 VARCHAR(50) ,   
   DIRECCION VARCHAR(50),   
   TELEFONO INTEGER,
   OCUPACION VARCHAR(50),      
   PRIMARY KEY (ID)    
   ); 
   
  CREATE TABLE ROLES
  (ID_ROL INT NOT NULL,  
   USUARIO VARCHAR(50),    
   CONTRASEÑA VARCHAR(50),	
   PRIMARY KEY (ID_ROL)          
   );

CREATE TABLE USUARIOS
  (ID_USUARIO INT NOT NULL,
   FK_CLIENTE INT,
   USUARIO VARCHAR(50),    
   CONTRASEÑA VARCHAR(50),
   ROL	INT,
   PRIMARY KEY (ID_USUARIO),
   FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTES(ID),
   FOREIGN KEY (ROL) REFERENCES ROLES(ID_ROL)             
   ); 

CREATE TABLE LIBROS
  (ID INT NOT NULL,
   FK_CLIENTE_LIBRO INT,
   TITULO VARCHAR(50) , 
   AUTOR VARCHAR(50) ,
   ANO_EDICION INTEGER ,  
   ISBM VARCHAR(50),
   GENERO VARCHAR(50),
   PAGINAS INTEGER,	
   PRIMARY KEY (ID),
   FOREIGN KEY (FK_CLIENTE_LIBRO) REFERENCES CLIENTES(ID)   
   ); 
CREATE TABLE EXISTENCIAS
  (ID INT NOT NULL,
   ID_LIBROS INT,    
   CANTIDAD INTEGER,	
   PRIMARY KEY (ID),
   FOREIGN KEY (ID_LIBROS) REFERENCES LIBROS(ID)          
   );

CREATE TABLE ELEMENTOS_MENU
  (ID_ELEMENTO INT NOT NULL,
   NOMBRE VARCHAR(50),    
   ICONO VARCHAR(50),	
   URL VARCHAR(50),
   PRIMARY KEY (ID_ELEMENTO)      
   );  

  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (1,"Santiago","Garcia","Rey","C/ Ave del paraiso 3",918823244,"Jardinero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (2,"Fernando","Tejero","Sanchez","C/ Ave del paraiso 3",918823244,"Coronel"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (3,"Felipe","Garcia","Sanchez","C/ Alcala 3",918823244,"Electronico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (4,"Emilio","Garcia","Sanchez","C/ Ave Rapaz 3",918768244,"Panadero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (5,"Fernando","Tejero","Sanchez","C/ Ave del paraiso 3",918295244,"Mecanico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (6,"Oscar","Martinez","Sanchez","C/ Alcala 3",918823326,"Electricista"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (7,"Santiago","Garcia","Rey","C/ Ave del paraiso 3",918823244,"Jardinero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (8,"Pepe","Lopez","Sanchez","C/ Ave del paraiso 3",918823244,"Programador"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (9,"Pedro","Garcia","Gomez","C/ Alcala 3",918823244,"Dependiente"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (10,"Sandro","Menezo","Sanchez","C/ Ave Rapaz 3",918768244,"Bombero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (11,"Cristina","Sanchez","Sanchez","C/ Alegoria 3",918295244,"Mecanico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (12,"Oscar","Taravillo","Sanchez","C/Madrid 3",918823326,"Medico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (13,"Marta","Garcia","Rey","C/ Ave del paraiso 3",918823244,"Jardinero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (14,"Susana","Tejero","Sanchez","C/Alondra 3",918823244,"Coronel"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (15,"Kandy","Garcia","Sanchez","C/Bitacora3",918823244,"Electronico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (16,"Virginia","Garcia","Sanchez","C/Belgica 3",918768244,"Panadero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (17,"Ruth","Tejero","Sanchez","C/ Averia 3",918295244,"Mecanico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (18,"Miriam","Martinez","Sanchez","C/ Alcala 3",918823326,"Electricista"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (19,"Roxana","Garcia","Rey","C/ Abeto 3",918823244,"Jardinero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (20,"Lucia","Lopez","Sanchez","C/Ave 3",918823244,"Programador"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (21,"Debora","Garcia","Gomez","C/ Alcala 3",918823244,"Dependiente"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (22,"Sandro","Menezo","Sanchez","C/Agora 3",918768244,"Bombero"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (23,"Cristina","Perez","Sanchez","C/Badiel 3",918295244,"Mecanico"); 
  INSERT INTO CLIENTES (ID,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TELEFONO,OCUPACION)	VALUES (24,"Oscar","Taravillo","Sanchez","C/Corintio 3",918823326,"Medico"); 

  